from __future__ import annotations

from dataclasses import dataclass, field
import json
import re
from typing import Any


@dataclass
class CodeGenerationRequest:
    requirement: str
    language: str
    context: str = ""
    constraints: list[str] = field(default_factory=list)
    include_tests: bool = True


@dataclass
class CodeGenerationResult:
    success: bool
    language: str
    requirement: str
    design: list[str] = field(default_factory=list)
    code: str = ""
    tests: str = ""
    notes: list[str] = field(default_factory=list)
    reason: str = ""


class CodeGenerator:
    """
    Task 5.4: LLM-backed Code Generation.

    Pipeline:
        requirement
            -> language
            -> design
            -> LLM
            -> code
            -> tests

    This module generates code but NEVER executes generated code.
    Execution is handled separately by Task 5.6.
    """

    SUPPORTED_LANGUAGES = {
        "Python",
        "JavaScript",
        "TypeScript",
        "HTML",
        "CSS",
        "SQL",
        "Bash",
        "PowerShell",
        "Java",
        "C",
        "C++",
        "C#",
        "Go",
        "Rust",
        "PHP",
        "Ruby",
        "Kotlin",
        "Swift",
        "Dart",
    }

    def __init__(self, llm_router: Any = None):
        self.llm_router = llm_router

    def generate(
        self,
        request: CodeGenerationRequest,
    ) -> CodeGenerationResult:
        requirement = request.requirement.strip()
        language = request.language.strip()

        if not requirement:
            return CodeGenerationResult(
                success=False,
                language=language,
                requirement=requirement,
                reason="Requirement cannot be empty.",
            )

        if language not in self.SUPPORTED_LANGUAGES:
            return CodeGenerationResult(
                success=False,
                language=language,
                requirement=requirement,
                reason=f"Unsupported language: {language}",
            )

        design = self._build_design(request)

        if self.llm_router is None:
            return CodeGenerationResult(
                success=False,
                language=language,
                requirement=requirement,
                design=design,
                reason="LLM router is not configured for code generation.",
            )

        prompt = self._build_generation_prompt(request, design)

        try:
            response = self.llm_router.generate(prompt)
        except Exception as exc:
            return CodeGenerationResult(
                success=False,
                language=language,
                requirement=requirement,
                design=design,
                reason=f"LLM code generation failed: {exc}",
            )

        parsed = self._parse_response(response)

        code = parsed.get("code", "").strip()
        tests = parsed.get("tests", "").strip()

        if not code:
            return CodeGenerationResult(
                success=False,
                language=language,
                requirement=requirement,
                design=design,
                reason="LLM returned no generated code.",
            )

        if not request.include_tests:
            tests = ""

        return CodeGenerationResult(
            success=True,
            language=language,
            requirement=requirement,
            design=design,
            code=code,
            tests=tests,
            notes=[
                "Code was generated by the configured LLM.",
                "Generated code must be reviewed before execution.",
                "Execution is intentionally handled by Task 5.6.",
                "Testing is intentionally handled by Task 5.7.",
            ],
            reason="Code generated successfully.",
        )

    def _build_design(
        self,
        request: CodeGenerationRequest,
    ) -> list[str]:
        design = [
            f"Target language: {request.language}",
            "Understand the requirement.",
            "Identify required inputs and outputs.",
            "Define functions/classes/modules as needed.",
            "Implement the smallest suitable solution.",
        ]

        if request.context.strip():
            design.append(
                "Use the supplied project/context information."
            )

        if request.constraints:
            design.append(
                "Respect the supplied implementation constraints."
            )

        if request.include_tests:
            design.append(
                "Create tests for the generated behavior."
            )

        return design

    def _build_generation_prompt(
        self,
        request: CodeGenerationRequest,
        design: list[str],
    ) -> str:
        constraints = "\n".join(
            f"- {item}"
            for item in request.constraints
        )

        context = request.context.strip()

        return f"""
You are the code-generation component of ISMAIL AI.

Generate production-quality code for the user's requirement.

TARGET LANGUAGE:
{request.language}

USER REQUIREMENT:
{request.requirement}

DESIGN:
{chr(10).join(f"- {item}" for item in design)}

PROJECT CONTEXT:
{context if context else "No additional project context was supplied."}

CONSTRAINTS:
{constraints if constraints else "No additional constraints were supplied."}

IMPORTANT RULES:
1. Return ONLY valid JSON.
2. Do not use Markdown code fences.
3. The JSON must contain:
   - "code": the complete implementation
   - "tests": tests for the implementation
4. The code must directly satisfy the requirement.
5. Do not leave TODO placeholders instead of implementation.
6. Do not execute commands.
7. Do not install packages.
8. Do not delete or modify files.
9. Do not include explanations outside the JSON.

Required JSON format:
{{
  "code": "generated source code",
  "tests": "generated test code"
}}
""".strip()

    def _parse_response(
        self,
        response: Any,
    ) -> dict[str, str]:
        if response is None:
            return {}

        text = str(response).strip()

        if not text:
            return {}

        # 1. Try JSON first.
        try:
            data = json.loads(text)

            if isinstance(data, dict):
                return {
                    "code": str(data.get("code", "")),
                    "tests": str(data.get("tests", "")),
                }
        except json.JSONDecodeError:
            pass

        # 2. Remove JSON Markdown fences and try again.
        cleaned = re.sub(
            r"^```(?:json)?\s*",
            "",
            text,
            flags=re.IGNORECASE,
        )

        cleaned = re.sub(
            r"\s*```$",
            "",
            cleaned,
        ).strip()

        try:
            data = json.loads(cleaned)

            if isinstance(data, dict):
                return {
                    "code": str(data.get("code", "")),
                    "tests": str(data.get("tests", "")),
                }
        except json.JSONDecodeError:
            pass

        # 3. Extract all Markdown code blocks.
        blocks = re.findall(
            r"```(?:[A-Za-z0-9_+#.-]+)?\s*\n?(.*?)```",
            text,
            flags=re.DOTALL,
        )

        if blocks:
            code = blocks[0].strip()
            tests = blocks[1].strip() if len(blocks) > 1 else ""

            # If the first block contains tests, split them out.
            test_markers = (
                "import unittest",
                "import pytest",
                "def test_",
                "class Test",
                "describe(",
                "it(",
                "test(",
            )

            test_position = -1

            for marker in test_markers:
                position = code.find(marker)
                if position > 0:
                    test_position = position
                    break

            if test_position > 0:
                tests = code[test_position:].strip()
                code = code[:test_position].strip()

            return {
                "code": code,
                "tests": tests,
            }

        # 4. Handle plain Python responses containing tests.
        test_markers = (
            "\nimport unittest",
            "\nimport pytest",
            "\ndef test_",
            "\nclass Test",
        )

        for marker in test_markers:
            position = text.find(marker)

            if position > 0:
                return {
                    "code": text[:position].strip(),
                    "tests": text[position:].strip(),
                }

        # 5. Last fallback: treat the complete response as code.
        return {
            "code": text,
            "tests": "",
        }


    


code_generator = CodeGenerator()