from backend.task_planner import TaskPlanner, TaskStep
# Representative output from a future/current capability selector.
# The selector does not need to know about TaskStep.
selected_capabilities = [
    {
        "capability": "research",
        "reason": "Current information is required.",
    },
    {
        "capability": "programming",
        "reason": "A Python solution is required.",
        "depends_on": ["research"],
    },
]
planner = TaskPlanner()
plan = planner.create_plan(
    capabilities=selected_capabilities
)
print("SELECTED:", selected_capabilities)
print("PLAN:", [
    (
        step.capability,
        step.action,
        step.reason,
        step.order,
    )
    for step in plan
])
# Boundary contract
assert isinstance(plan, list)
assert all(isinstance(step, TaskStep) for step in plan)
# Dependency must be respected.
assert [step.capability for step in plan] == [
    "research",
    "programming",
]
# Actions must come from the planner, not the selector.
assert plan[0].action == "research"
assert plan[1].action == "analyze_or_execute"
# Reasons must pass through.
assert plan[0].reason == "Current information is required."
assert plan[1].reason == "A Python solution is required."
# Execution order must be generated by planner.
assert [step.order for step in plan] == [1, 2]
print("TASK4_STEP12_BOUNDARY_OK")
