from backend.ai_engine import AIEngine
engine = AIEngine()
print("HAS_RESEARCH:", hasattr(engine, "web_research"))
print("HAS_PROGRAMMING:", hasattr(engine, "programming_intelligence"))
print("HAS_VERIFIER:", hasattr(engine, "result_verifier"))
print("HAS_TASK_PLANNER:", hasattr(engine, "task_planner"))
print("HAS_CAPABILITY_SELECTOR:", hasattr(engine, "capability_selector"))
assert hasattr(engine, "web_research")
assert hasattr(engine, "programming_intelligence")
assert hasattr(engine, "result_verifier")
assert hasattr(engine, "task_planner")
assert hasattr(engine, "capability_selector")
print("RESEARCH_TYPE:", type(engine.web_research).__name__)
print("PROGRAMMING_TYPE:", type(engine.programming_intelligence).__name__)
print("VERIFIER_TYPE:", type(engine.result_verifier).__name__)
print("PLANNER_TYPE:", type(engine.task_planner).__name__)
print("SELECTOR_TYPE:", type(engine.capability_selector).__name__)
print("TASK4_STEP43_ORCHESTRATOR_DEPENDENCIES_OK")
